version: "3.8"
volumes:
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres-sq:5432/postgres
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=mypassword123
    restart: always

  postgres-sq:
    image: postgres
    volumes:
      - /home/rocky/postgres-sq/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword123
    restart: always
