- name: Install optional packages for all servers
  hosts: all
  become: true
  tasks:
    - name: Install list of packages
      ansible.builtin.dnf:
        name:
          - nginx
          - go
        state: present

- name: Install Ansible on masters servers
  hosts: masters
  become: true
  tasks:
    - name: Install Ansible
      pip:
        name:
          - ansible
      vars:
        ansible_python_interpreter: /usr/bin/python3.9

- name: Install pnpm for masters servers
  hosts: masters
  become: true
  tasks:
    - name: Install pnpm
      community.general.npm:
        name: pnpm
        global: true
        state: present

- name: Install Docker-CE
  hosts: all
  become: true
  tasks:
    - name: Install dnf-utils
      ansible.builtin.dnf:
        name: dnf-utils
        state: present
    - name: Add DNF config
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      changed_when: false
    - name: Install Docker and its deps
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
    - name: Enable and start docker service
      systemd:
        name: docker
        enabled: true
        state: started
