- name: Setup Docker Registry
  hosts: masters
  become: true
  tasks:
    - name: Run Docker registry
      community.docker.docker_container:
        name: registry
        image: registry:latest
        state: started
        pull: true
        restart_policy: always
        env:
          REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        volumes:
          - ./data:/data
        ports:
          - "5000:5000"

- name: Add CICD server Docker insecure registry
  hosts: masters
  become: true
  tasks:
    - name: Copy file over
      ansible.builtin.copy:
        src: ../config-files/daemon.json
        dest: /etc/docker/daemon.json
        mode: "444"
