- name: Configure Nginx Reverse Proxies
  hosts: norcal
  become: true
  tasks:
    - name: Set Uptime Kuma Reverse Proxy
      ansible.builtin.copy:
        src: ../config-files/uptime-kuma.conf
        dest: /etc/nginx/conf.d/uptime-kuma.conf
        mode: "400"

    - name: Enable and start nginx service
      systemd:
        name: nginx
        enabled: true
        state: restarted
